export const ELEMENT_NAMES: Record<string, string> = {
  H: 'hidrógeno',
  He: 'helio',
  Li: 'litio',
  Be: 'berilio',
  B: 'boro',
  C: 'carbono',
  N: 'nitrógeno',
  O: 'oxígeno',
  F: 'flúor',
  Ne: 'neón',
  Na: 'sodio',
  Mg: 'magnesio',
  Al: 'aluminio',
  Si: 'silicio',
  P: 'fósforo',
  S: 'azufre',
  Cl: 'cloro',
  Ar: 'argón',
  K: 'potasio',
  Ca: 'calcio',
  Sc: 'escandio',
  Ti: 'titanio',
  V: 'vanadio',
  Cr: 'cromo',
  Mn: 'manganeso',
  Fe: 'hierro',
  Co: 'cobalto',
  Ni: 'níquel',
  Cu: 'cobre',
  Zn: 'zinc',
  Ga: 'galio',
  Ge: 'germanio',
  As: 'arsénico',
  Se: 'selenio',
  Br: 'bromo',
  Kr: 'kriptón',
  Rb: 'rubidio',
  Sr: 'estroncio',
  Y: 'itrio',
  Zr: 'circonio',
  Nb: 'niobio',
  Mo: 'molibdeno',
  Tc: 'tecnecio',
  Ru: 'rutenio',
  Rh: 'rodio',
  Pd: 'paladio',
  Ag: 'plata',
  Cd: 'cadmio',
  In: 'indio',
  Sn: 'estaño',
  Sb: 'antimonio',
  Te: 'telurio',
  I: 'yodo',
  Xe: 'xenón',
  Cs: 'cesio',
  Ba: 'bario',
  La: 'lantano',
  Ce: 'cerio',
  Pr: 'praseodimio',
  Nd: 'neodimio',
  Pm: 'prometio',
  Sm: 'samario',
  Eu: 'europio',
  Gd: 'gadolinio',
  Tb: 'terbio',
  Dy: 'disprosio',
  Ho: 'holmio',
  Er: 'erbio',
  Tm: 'tulio',
  Yb: 'iterbio',
  Lu: 'lutecio',
  Hf: 'hafnio',
  Ta: 'tántalo',
  W: 'wolframio',
  Re: 'renio',
  Os: 'osmio',
  Ir: 'iridio',
  Pt: 'platino',
  Au: 'oro',
  Hg: 'mercurio',
  Tl: 'talio',
  Pb: 'plomo',
  Bi: 'bismuto',
  Po: 'polonio',
  At: 'astato',
  Rn: 'radón',
  Fr: 'francio',
  Ra: 'radio',
  Ac: 'actinio',
  Th: 'torio',
  Pa: 'protactinio',
  U: 'uranio',
  Np: 'neptunio',
  Pu: 'plutonio',
  Am: 'americio',
  Cm: 'curio',
  Bk: 'berkelio',
  Cf: 'californio',
  Es: 'einstenio',
  Fm: 'fermio',
  Md: 'mendelevio',
  No: 'nobelio',
  Lr: 'lawrencio',
  Rf: 'rutherfordio',
  Db: 'dubnio',
  Sg: 'seaborgio',
  Bh: 'bohrio',
  Hs: 'hasio',
  Mt: 'meitnerio',
  Ds: 'darmstatio',
  Rg: 'roentgenio',
  Cn: 'copernicio',
  Nh: 'nihonio',
  Fl: 'flerovio',
  Mc: 'moscovio',
  Lv: 'livermorio',
  Ts: 'teneso',
  Og: 'oganesón',
}

export type EquationElement = { symbol: string; name: string }

// Devuelve los elementos distintos de una ecuación, en orden de aparición.
// Los nombres salen de este diccionario, nunca del modelo.
export function extractElements(equation: string): EquationElement[] {
  const seen = new Set<string>()
  const found: EquationElement[] = []

  for (const match of equation.matchAll(/[A-Z][a-z]?/g)) {
    const symbol = match[0]
    const name = ELEMENT_NAMES[symbol]
    if (name && !seen.has(symbol)) {
      seen.add(symbol)
      found.push({ symbol, name })
    }
  }

  return found
}